### PR TITLE
SFLW-9/abilaash/create work for us

### PR DESCRIPTION
**Pull request by Abilaash01**

### CODE REVIEW

**Review by CoderHahs — CHANGES_REQUESTED** [review]
Please remove scrollbar from testimonials -> work with @AvaneeshM & @dhari001 to get shorter text

**Review by AvaneeshM — APPROVED** [review]

**Comment by CoderHahs** [comment]
@Suri111200, @dhari001 what do you think about the text, I feel it should be the same font as the rest of our site.

**Review by CoderHahs — APPROVED** [review]
The scrollbar issue is now fixed good job! We can merge it in, but I would like to get @dhari001 and @Suri111200 to look at font and if it needs to be fixed.

**Comment by AvaneeshM** [comment]
> The scrollbar issue is now fixed good job! We can merge it in, but I would like to get @dhari001 and @Suri111200 to look at font and if it needs to be fixed.

**Review by dhari001 — APPROVED** [review]

**Comment by dhari001** [comment]
> The scrollbar issue is now fixed good job! We can merge it in, but I would like to get @dhari001 and @Suri111200 to look at font and see if it needs to be fixed.

has the font been changed to accomodate more words and keep the scrollbar out? if yes, then keep the font otherwise change it to what we typically use for the site for consistency purposes

**Comment by dhari001** [comment]
> > The scrollbar issue is now fixed good job! We can merge it in, but I would like to get @dhari001 and @Suri111200 to look at font and see if it needs to be fixed.
> 
> has the font been changed to accomodate more words and keep the scrollbar out? if yes, then keep the font otherwise change it to what we typically use for the site for consistency purposes

@Abilaash01 ^

**Review by CoderHahs — APPROVED** [review]
Looks good to me, can be merged!

**Review by CoderHahs — CHANGES_REQUESTED** [review]
Sorry noticed one last thing, super small. If we can make sure that arrows don't disappear when mouse hovers that would be great. Changing color is fine, or any subtle style change so that user knows that its a button is fine. Disappearing buttons are frowned upon!

**Review by CoderHahs — APPROVED** [review]
Changes look good! Thank you for being patient with me and fixing the small things. PR can be merged!

**Pull request merged**
