### PR TITLE
Changed Landing Image next to "Our Values" + Made "Interests" a mandatory field

### LINKED ISSUE #74: Change Landing Image next to "Our Values" on Organization Page
- Seems inconsistent/odd compared to other pages

### PR DESCRIPTION
**Pull request by kandloic**
## Added a new image next to Our Values
image

## Made Interests a mandatory field
- User must check off at least one interest in order to submit volunteer form

Fixes #74

### CODE REVIEW

**Comment by CoderHahs** [comment]
Is the Our Values background purple? Based on the image I see white, which is not consistent with the rest of the site.

**Comment by kandloic** [comment]
> Is the Our Values background purple? Based on the image I see white, which is not consistent with the rest of the site.

The _Our Values_ background is gray. During our meeting, I brought up the fact that keeping a blue background on the secondary pages (Organizations, Volunteers, etc...) makes it seem like the user never left the landing page so I proposed to change it to gray and the rest of the team were on board with it.

Would you prefer I change it back to blue?

**Comment by Suri111200** [comment]
@CoderHahs Haven't had a chance to check out this PR in detail, but we discussed in our last meeting that we wanted to change the background colour of the top section on some pages to be different, so that there are more differences between the pages. I've told @kandloic @Renfrew100 and @AvaneeshM to change the colours to other suitable colours in our scheme for their respective pages. We should discuss this further if you don't think that's a good idea

**Comment by Suri111200** [comment]
Resolved -- changed the colours back

**Pull request merged**
