### PR TITLE
Modified content on site

### PR DESCRIPTION
**Pull request by Suri111200**
Revised donation page content (as per Suhavi's request), modified main page content, changed link colour in footer (for some reason it just matched the background and was invisible).

### CODE REVIEW

**Comment by Suri111200** [comment]
Will be presenting this to the exec team + requesting for feedback

@CoderHahs I welcome your feedback as well.

**Review by dhari001 — APPROVED** [review]

**Comment by CoderHahs** [comment]
Does this address the mobile issue?

**Comment by CoderHahs** [comment]
Donation page, main section should have title left justified. 

Middle section should have more content, let's add more specifics about each non profit, what we did for them. Add specfiically how these donations will help us. **We should also add links to each charity/non-profit image!**

Main page: When I come to visit the site for the first time, I don't see anything about how we do all the work for free. If we can communicate that to clients in less than 5 seconds from visiting our site, I think that would be ideal.

Also if we are revising content, **THE ORGANIZATION PAGE NEEDS TO BE REVISED ASAP**. We need to remove that we donate to charities, and highlight that we do free work. If we can push that with this merge that would be ideal.

Last thing, can we please change the alert format. I've mentioned this countless times, but that alert is not how a typical alert looks like. Refer to this: https://dribbble.com/shots/16521605-Toast-NUX (alerts on the right) for an example of good alert design We should probably remove it now, and just have it be linked to our Organization page. We can get started on 2022 In Review and add that as a alert once its finished.

**Review by CoderHahs — CHANGES_REQUESTED** [review]
Left comments above on changes to be made

**Comment by Suri111200** [comment]
@CoderHahs FYI, the mobile issue has been resolved in [this PR](https://github.com/Software-For-Love/software-for-love-site/pull/257).

**Comment by CoderHahs** [comment]
> @CoderHahs FYI, the mobile issue has been resolved in [this PR](https://github.com/Software-For-Love/software-for-love-site/pull/257).

Saw it, looks good. I see the link in the privacy policy link is hidden (I'm assuming this was taken care of in this PR).

**Pull request merged**
